In [1]:
import numpy as np

In [2]:
arr = np.array([3,5,7,9,45])

In [5]:
int(np.mean(arr))

13

In [6]:
np.min(arr)

np.int64(3)

In [7]:
np.max(arr)

np.int64(45)

In [8]:
np.sum(arr)

np.int64(69)

In [9]:
np.prod(arr)

np.int64(42525)

In [10]:
np.std(arr)

np.float64(15.727682601069999)

In [11]:
np.median(arr)

np.float64(7.0)

In [13]:
np.percentile(arr, 50)

np.float64(7.0)

In [14]:
np.diff(arr)

array([ 2,  2,  2, 36])

In [15]:
np.cumsum(arr)

array([ 3,  8, 15, 24, 69])

In [17]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [18]:
np.argmin(arr)

np.int64(0)

In [19]:
np.argmax(arr)

np.int64(4)

In [20]:
np.corrcoef(arr)

np.float64(1.0)

In [21]:
np.unique(arr)

array([ 3,  5,  7,  9, 45])

In [22]:
np.exp(arr)

array([2.00855369e+01, 1.48413159e+02, 1.09663316e+03, 8.10308393e+03,
       3.49342711e+19])

In [23]:
np.diff(arr)

array([ 2,  2,  2, 36])