In [1]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7, 8, 9],[10,11,12]])

In [2]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [3]:
flat = arr.flatten()

In [4]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [5]:
flat[0]

np.int64(1)

In [7]:
flat[3:6]

array([4, 5, 6])

In [8]:
flat[:6]

array([1, 2, 3, 4, 5, 6])

In [10]:
flat[3:] #[3:13]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [11]:
flat[3:13]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [12]:
flat[::2]

array([ 1,  3,  5,  7,  9, 11])

In [13]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [18]:
b = flat[3:7].copy # this is not a slice bcz we are using copy methd to get the copy

In [15]:
b[0] = 222

In [16]:
b

array([222,   5,   6,   7])

In [19]:
flat

array([  1,   2,   3, 222,   5,   6,   7,   8,   9,  10,  11,  12])

## Fancy Indexing & Boolean Masking ##

In [25]:
arr1 = np.array([1,54,2,3,23,34,5,6])

In [27]:
arr1[[0,4,6]]

array([ 1, 23,  5])

In [28]:
arr = np.array([10, 20, 30, 40, 50])
mask = arr > 25  # Condition: values greater than 25
print(arr[mask])  

[30 40 50]
