In [2]:
import numpy as np
arr = np.array([[1,2,3],
                [4, 5, 6], 
                [7, 8, 9]])

In [3]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
arr[0]

array([1, 2, 3])

In [5]:
arr[1]

array([4, 5, 6])

In [6]:
np.sum(arr, axis=0) # 0 corresponds to row i,e 1+4+7 

array([12, 15, 18])

In [7]:
np.sum(arr, axis=1) # 1 corresponds to column i,e 1+2+3

array([ 6, 15, 24])

# Indexing in Multidimensional Arrays

In [9]:
int(arr[0][1])

2

In [10]:
arr[0,1]

np.int64(2)

In [11]:
arr[0:2, 1:3]

array([[2, 3],
       [5, 6]])

# Indexing  in 3D Arrays

In [13]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9],  [10, 11, 12]]])

In [14]:
arr3D.shape

(2, 2, 3)

In [16]:
int(arr3D[0,1,2])

6

In [21]:
arr3D[:, 0, :]

array([[1, 2, 3],
       [7, 8, 9]])