# Numpy Tutorials

In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,6,37,7]], np.int64)

In [3]:
myarr

array([[ 3,  6, 37,  7]])

In [4]:
myarr[0]

array([ 3,  6, 37,  7])

In [5]:
myarr[0,1]

np.int64(6)

In [6]:
myarr.shape

(1, 4)

In [7]:
myarr.dtype

dtype('int64')

In [8]:
myarr

array([[ 3,  6, 37,  7]])

# Array creation : Conversion from other Python structures

In [10]:
listarray = np.array([[1,2,3],[5,6,7],[0,3,1]])

In [11]:
listarray

array([[1, 2, 3],
       [5, 6, 7],
       [0, 3, 1]])

In [12]:
listarray.dtype

dtype('int64')

In [13]:
listarray.shape

(3, 3)

In [14]:
listarray.size

9

In [15]:
np.array({34,38,34})

array({34, 38}, dtype=object)

In [16]:
zeros = np.zeros((2, 5))

In [17]:
zeros.dtype

dtype('float64')

In [18]:
zeros.size

10

In [19]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
rng = np.arange(15)

In [22]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
lspace = np.linspace(1,5,4)

In [28]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [29]:
emp = np.empty((4,6))

In [30]:
emp

array([[6.23042070e-307, 1.86918699e-306, 1.69121096e-306,
        1.22383221e-307, 7.56587584e-307, 7.56593017e-307],
       [1.24610383e-306, 1.24610723e-306, 1.37962320e-306,
        1.29060871e-306, 2.22522597e-306, 1.33511969e-306],
       [1.78022342e-306, 1.05700345e-307, 1.24610383e-306,
        1.69118108e-306, 8.06632139e-308, 1.20160711e-306],
       [1.69119330e-306, 1.29062229e-306, 1.24610383e-306,
        6.89804132e-307, 1.69121096e-306, 8.34449382e-308]])

In [31]:
emp_like = np.empty_like(lspace)

In [32]:
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [33]:
ide = np.identity(45)

In [34]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [35]:
ide.shape

(45, 45)

In [36]:
arr1 = np.arange(99)

In [37]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [39]:
arr1.reshape(3, 33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [40]:
arr1.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [42]:
arr1.shape

(99,)

# Axis

In [43]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [44]:
ar = np.array(x)

In [45]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [49]:
ar.sum(axis=0)

array([12,  8,  9])

In [50]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [52]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [53]:
ar.flat

In [54]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [55]:
ar.ndim

2

In [56]:
ar.size

9

In [57]:
ar.nbytes

72

In [58]:
one = np.array([1,3,4,634,2])

In [59]:
one.argmax()

np.int64(3)

In [60]:
int(one.argmax())

3

In [61]:
one.argmin()

np.int64(0)

In [62]:
int(one.argmin())

0

In [63]:
one.argsort()

array([0, 4, 1, 2, 3])

In [66]:
int(ar.argmin())

8

In [67]:
int(ar.argmax())

6

In [68]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [69]:
ar.argmax(axis=0)

array([2, 1, 1])

In [70]:
ar.argmax(axis=1)

array([2, 2, 0])

In [71]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [72]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [75]:
ar.reshape((9,))

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [76]:
ar2 = np.array([[1,2,1], [4,0,6],[8,1,0]])
    

In [77]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [78]:
[1 , 3] + [46 , 6]

[1, 3, 46, 6]

In [79]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [80]:
np.sqrt(ar2)

array([[1.        , 1.41421356, 1.        ],
       [2.        , 0.        , 2.44948974],
       [2.82842712, 1.        , 0.        ]])

In [82]:
int(ar.sum())

29

In [83]:
int(ar.max())

7

In [84]:
int(ar.min())

0

In [85]:
np.where(ar>5)

(array([1, 2]), array([2, 0]))

In [86]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [87]:
type(np.where(ar>5))

tuple

In [88]:
np.count_nonzero(ar)

8

In [89]:
import sys

In [91]:
py_ar = [0, 4,55, 2]

In [92]:
np_ar = np.array(py_ar)

In [93]:
np_ar

array([ 0,  4, 55,  2])

In [94]:
sys.getsizeof(1) * len(py_ar)

112

In [95]:
np_ar.itemsize * np_ar.size

32

In [96]:
np_ar.tolist()

[0, 4, 55, 2]