# Performance test

In [9]:
#Using python lists
import numpy as np
import time

size = 1_000_000
start = time.time()
l1 = list(range(size))
l2 = list(range(size))

start = time.time()
add = [x+y for x,y in zip(l1, l2)]
print(add[0:10])
end = time.time()
print(end - start)


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
0.10408592224121094


In [10]:
#using numpy array
import numpy as np
import time

size = 1_000_000
start = time.time()
l1 = np.array(list(range(size)))
l2 = np.array(list(range(size)))

start = time.time()
# add = [x+y for x,y in zip(l1, l2)]
add = l1 + l2
print(add[0:10])
end = time.time()
print(end - start)


[ 0  2  4  6  8 10 12 14 16 18]
0.023067712783813477


In [4]:
l1 = [1,2,4]
l2 = [6,7, 8]

In [5]:
list(zip(l1,l2))

[(1, 6), (2, 7), (4, 8)]

In [11]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [16]:
arr = np.array([[1,2,3],[4,5,6]])

In [17]:
type(arr)

numpy.ndarray

In [18]:
arr.shape

(2, 3)

In [49]:
#time taken to multiply two python list vs numpy arrays

import numpy as np
import time

#python list
l1 = [2,3]
l2 = [4, 5]
start = time.time()
multiply = [ x * y for x,y in zip(l1,l2)]
print(multiply)
end = time.time()
print(end-start)


[8, 15]
0.0009968280792236328


In [51]:
l1 = np.array([2,3])
l2 = np.array([4, 5])
start = time.time()
multiply = l1 * l2
print(multiply)
end = time.time()
print(end-start)

[ 8 15]
0.0008258819580078125


# Memory Efficiency

In [20]:
import sys

list_data = list(range(1000))
numpy_data = np.array(list_data)

print("Python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")
print("NumPy array size:", numpy_data.nbytes, "bytes")

Python list size: 8056000 bytes
NumPy array size: 8000 bytes


In [28]:
# Python list (loop-based)
size = 10
list1 = list(range(size))

start = time.time()
list_squares = [x ** 2 for x in list1]
print(list_squares)
end = time.time()
print(end - start)


[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
0.0013957023620605469


In [32]:
size = 10
arr1 = np.array(list(range(size)))
start = time.time()
numpy_squares = arr1 ** 2
print(numpy_squares)
end = time.time()
print(end - start)

[ 0  1  4  9 16 25 36 49 64 81]
0.0010941028594970703


In [40]:
# Create a NumPy array with values from 10 to 100 and print its shape.
np_arr = np.arange(10,101)

In [39]:
print(np_arr.shape)

(91,)
